name: Testing CI workflow

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: build 
        run: mkdir build 
             cd build 
             cmake ..
             make

      - name: Run tests
        run: ./runStackTests