name: Dojo_Status

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4 # Always a good idea to checkout the code first

    - name: Configure CMake
      run: |
        cmake -B ${{github.workspace}}/build -S ${{github.workspace}}

    - name: Build project
      run: cmake --build ${{github.workspace}}/build

    - name: Run tests
      working-directory: ${{github.workspace}}/build
      # Run tests after building
      run: ./runStackTests